name: ancres-logicielles

services:
  appserver:
    build:
      context: "deployment/frankenphp"
    env_file:
      - "deployment/default.env"
    volumes:
      - "./app:/app:Z"
    ports:
      - target: 443
        published: 8443
        protocol: tcp
    networks:
      - app-internal
    depends_on:
      database:
        condition: service_started

  database:
    build:
      context: "deployment/database"
    env_file:
      - "deployment/default.env"
    volumes:
      - "database:/var/lib/mysql"
    networks:
      - app-internal

volumes:
  database:
    driver: local

networks:
  app-internal: {}
