services:
  appserver:
    build:
      context: "deployment/frankenphp"
    env_file:
      - "deployment/default.env"
    volumes:
      - "./app:/app:Z"
    ports:
      - "127.0.0.1:8443:443"
    networks:
      - app-internal
    depends_on:
      database:
        condition: service_started

  database:
    build:
      context: "deployment/database"
    env_file:
      - "deployment/default.env"
    volumes:
      - "database:/var/lib/mysql"
    networks:
      - app-internal

volumes:
  database:

networks:
  app-internal: {}